<?php

class SomethingDigital_EnterpriseIndexPerf_Model_Url_Rewrite_Category_Refresh
    extends Enterprise_Catalog_Model_Index_Action_Url_Rewrite_Category_Refresh
{
    use SomethingDigital_EnterpriseIndexPerf_Trait_Url_CategoryRewriteCache;
}
